// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using payApp.API.Data;

namespace payApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190811231732_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("payApp.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Costs");

                    b.Property<int>("Income");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("payApp.API.Models.Wish", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Cost");

                    b.Property<string>("Name");

                    b.Property<string>("UrlToShop");

                    b.Property<int?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Wishes");
                });

            modelBuilder.Entity("payApp.API.Models.Wish", b =>
                {
                    b.HasOne("payApp.API.Models.User", "User")
                        .WithMany("UserWishes")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
